import emoji
print()
print(emoji.emojize('Seja bem vindo! :raising_hand:', use_aliases=True))
print()
print('-' * 30)
print()
print('-' * 30)
print()
print('Acesse meu github! \n\nhttps://github.com/tarcisioribeiro')
print()